// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/rpc/necoperf.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerfProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfProfileRequest) Reset() {
	*x = PerfProfileRequest{}
	mi := &file_internal_rpc_necoperf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfProfileRequest) ProtoMessage() {}

func (x *PerfProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_necoperf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfProfileRequest.ProtoReflect.Descriptor instead.
func (*PerfProfileRequest) Descriptor() ([]byte, []int) {
	return file_internal_rpc_necoperf_proto_rawDescGZIP(), []int{0}
}

func (x *PerfProfileRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PerfProfileRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type PerfProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerfProfileResponse) Reset() {
	*x = PerfProfileResponse{}
	mi := &file_internal_rpc_necoperf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerfProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfProfileResponse) ProtoMessage() {}

func (x *PerfProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_rpc_necoperf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfProfileResponse.ProtoReflect.Descriptor instead.
func (*PerfProfileResponse) Descriptor() ([]byte, []int) {
	return file_internal_rpc_necoperf_proto_rawDescGZIP(), []int{1}
}

func (x *PerfProfileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_rpc_necoperf_proto protoreflect.FileDescriptor

const file_internal_rpc_necoperf_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/rpc/necoperf.proto\x12\bnecoperf\x1a\x1egoogle/protobuf/duration.proto\"l\n" +
	"\x12PerfProfileRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\")\n" +
	"\x13PerfProfileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data2T\n" +
	"\bNecoPerf\x12H\n" +
	"\aProfile\x12\x1c.necoperf.PerfProfileRequest\x1a\x1d.necoperf.PerfProfileResponse0\x01B,Z*github.com/cybozu-go/necoperf/internal/rpcb\x06proto3"

var (
	file_internal_rpc_necoperf_proto_rawDescOnce sync.Once
	file_internal_rpc_necoperf_proto_rawDescData []byte
)

func file_internal_rpc_necoperf_proto_rawDescGZIP() []byte {
	file_internal_rpc_necoperf_proto_rawDescOnce.Do(func() {
		file_internal_rpc_necoperf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_rpc_necoperf_proto_rawDesc), len(file_internal_rpc_necoperf_proto_rawDesc)))
	})
	return file_internal_rpc_necoperf_proto_rawDescData
}

var file_internal_rpc_necoperf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_rpc_necoperf_proto_goTypes = []any{
	(*PerfProfileRequest)(nil),  // 0: necoperf.PerfProfileRequest
	(*PerfProfileResponse)(nil), // 1: necoperf.PerfProfileResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_internal_rpc_necoperf_proto_depIdxs = []int32{
	2, // 0: necoperf.PerfProfileRequest.timeout:type_name -> google.protobuf.Duration
	0, // 1: necoperf.NecoPerf.Profile:input_type -> necoperf.PerfProfileRequest
	1, // 2: necoperf.NecoPerf.Profile:output_type -> necoperf.PerfProfileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_rpc_necoperf_proto_init() }
func file_internal_rpc_necoperf_proto_init() {
	if File_internal_rpc_necoperf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_rpc_necoperf_proto_rawDesc), len(file_internal_rpc_necoperf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_rpc_necoperf_proto_goTypes,
		DependencyIndexes: file_internal_rpc_necoperf_proto_depIdxs,
		MessageInfos:      file_internal_rpc_necoperf_proto_msgTypes,
	}.Build()
	File_internal_rpc_necoperf_proto = out.File
	file_internal_rpc_necoperf_proto_goTypes = nil
	file_internal_rpc_necoperf_proto_depIdxs = nil
}
