// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: internal/rpc/necoperf.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NecoPerf_Profile_FullMethodName = "/necoperf.NecoPerf/Profile"
)

// NecoPerfClient is the client API for NecoPerf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NecoPerfClient interface {
	Profile(ctx context.Context, in *PerfProfileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PerfProfileResponse], error)
}

type necoPerfClient struct {
	cc grpc.ClientConnInterface
}

func NewNecoPerfClient(cc grpc.ClientConnInterface) NecoPerfClient {
	return &necoPerfClient{cc}
}

func (c *necoPerfClient) Profile(ctx context.Context, in *PerfProfileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PerfProfileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NecoPerf_ServiceDesc.Streams[0], NecoPerf_Profile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PerfProfileRequest, PerfProfileResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NecoPerf_ProfileClient = grpc.ServerStreamingClient[PerfProfileResponse]

// NecoPerfServer is the server API for NecoPerf service.
// All implementations must embed UnimplementedNecoPerfServer
// for forward compatibility.
type NecoPerfServer interface {
	Profile(*PerfProfileRequest, grpc.ServerStreamingServer[PerfProfileResponse]) error
	mustEmbedUnimplementedNecoPerfServer()
}

// UnimplementedNecoPerfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNecoPerfServer struct{}

func (UnimplementedNecoPerfServer) Profile(*PerfProfileRequest, grpc.ServerStreamingServer[PerfProfileResponse]) error {
	return status.Error(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedNecoPerfServer) mustEmbedUnimplementedNecoPerfServer() {}
func (UnimplementedNecoPerfServer) testEmbeddedByValue()                  {}

// UnsafeNecoPerfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NecoPerfServer will
// result in compilation errors.
type UnsafeNecoPerfServer interface {
	mustEmbedUnimplementedNecoPerfServer()
}

func RegisterNecoPerfServer(s grpc.ServiceRegistrar, srv NecoPerfServer) {
	// If the following call panics, it indicates UnimplementedNecoPerfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NecoPerf_ServiceDesc, srv)
}

func _NecoPerf_Profile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PerfProfileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NecoPerfServer).Profile(m, &grpc.GenericServerStream[PerfProfileRequest, PerfProfileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NecoPerf_ProfileServer = grpc.ServerStreamingServer[PerfProfileResponse]

// NecoPerf_ServiceDesc is the grpc.ServiceDesc for NecoPerf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NecoPerf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "necoperf.NecoPerf",
	HandlerType: (*NecoPerfServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Profile",
			Handler:       _NecoPerf_Profile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/rpc/necoperf.proto",
}
