// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.2
// source: pkg/rpc/necoperf.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PerfProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContainerId string               `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Timeout     *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *PerfProfileRequest) Reset() {
	*x = PerfProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_necoperf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfProfileRequest) ProtoMessage() {}

func (x *PerfProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_necoperf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfProfileRequest.ProtoReflect.Descriptor instead.
func (*PerfProfileRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_necoperf_proto_rawDescGZIP(), []int{0}
}

func (x *PerfProfileRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *PerfProfileRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type PerfProfileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PerfProfileResponse) Reset() {
	*x = PerfProfileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_rpc_necoperf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfProfileResponse) ProtoMessage() {}

func (x *PerfProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_necoperf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfProfileResponse.ProtoReflect.Descriptor instead.
func (*PerfProfileResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_necoperf_proto_rawDescGZIP(), []int{1}
}

func (x *PerfProfileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pkg_rpc_necoperf_proto protoreflect.FileDescriptor

var file_pkg_rpc_necoperf_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x65, 0x63, 0x6f, 0x70, 0x65,
	0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x63, 0x6f, 0x70, 0x65,
	0x72, 0x66, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x66, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x74,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x22, 0x29, 0x0a, 0x13, 0x50, 0x65, 0x72, 0x66, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x54, 0x0a, 0x08, 0x4e,
	0x65, 0x63, 0x6f, 0x50, 0x65, 0x72, 0x66, 0x12, 0x48, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x12, 0x1c, 0x2e, 0x6e, 0x65, 0x63, 0x6f, 0x70, 0x65, 0x72, 0x66, 0x2e, 0x50, 0x65,
	0x72, 0x66, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x6e, 0x65, 0x63, 0x6f, 0x70, 0x65, 0x72, 0x66, 0x2e, 0x50, 0x65, 0x72, 0x66,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x79, 0x62, 0x6f, 0x7a, 0x75, 0x2d, 0x67, 0x6f, 0x2f, 0x6e, 0x65, 0x63, 0x6f, 0x70, 0x65,
	0x72, 0x66, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_rpc_necoperf_proto_rawDescOnce sync.Once
	file_pkg_rpc_necoperf_proto_rawDescData = file_pkg_rpc_necoperf_proto_rawDesc
)

func file_pkg_rpc_necoperf_proto_rawDescGZIP() []byte {
	file_pkg_rpc_necoperf_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_necoperf_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_rpc_necoperf_proto_rawDescData)
	})
	return file_pkg_rpc_necoperf_proto_rawDescData
}

var file_pkg_rpc_necoperf_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_rpc_necoperf_proto_goTypes = []interface{}{
	(*PerfProfileRequest)(nil),  // 0: necoperf.PerfProfileRequest
	(*PerfProfileResponse)(nil), // 1: necoperf.PerfProfileResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_pkg_rpc_necoperf_proto_depIdxs = []int32{
	2, // 0: necoperf.PerfProfileRequest.timeout:type_name -> google.protobuf.Duration
	0, // 1: necoperf.NecoPerf.Profile:input_type -> necoperf.PerfProfileRequest
	1, // 2: necoperf.NecoPerf.Profile:output_type -> necoperf.PerfProfileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_necoperf_proto_init() }
func file_pkg_rpc_necoperf_proto_init() {
	if File_pkg_rpc_necoperf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_rpc_necoperf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_rpc_necoperf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PerfProfileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_rpc_necoperf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_necoperf_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_necoperf_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_necoperf_proto_msgTypes,
	}.Build()
	File_pkg_rpc_necoperf_proto = out.File
	file_pkg_rpc_necoperf_proto_rawDesc = nil
	file_pkg_rpc_necoperf_proto_goTypes = nil
	file_pkg_rpc_necoperf_proto_depIdxs = nil
}
