name: CI
on:
  pull_request:
  push:
    branches:
    - 'main'
jobs:
  test:
    name: Small tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - run: make setup
      - run: make check-generated
      - run: make lint
      - run: make test
      - run: make build
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - run: make setup
      - run: make -C e2e setup
      - run: make -C e2e start
      - run: make -C e2e test
      - run: make -C e2e show-log
        if: always()
  perf:
    name: Run perf on CI env
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: make run-perf
